import Head from 'next/head';
import * as React from 'react';
import Navbar from './Navbar';

interface ILayoutProps {
	children: React.ReactNode;
}

const Layout: React.FunctionComponent<ILayoutProps> = ({ children }) => {
	return (
		<>
			<Head>
				<title>Moro Owusu Afriyie</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
				></link>
			</Head>
			<div className="h-screen flex font-poppins">
				<header className="header h-full overflow-y-auto w-[17.5rem] bg-blue-gradient text-white">
					<Navbar />
				</header>
				{/* <aside className="sidebar h-full  border-red-900  overflow-y-auto w-[17.5rem]">
				<Sidebar />
			</aside> */}
				<main className="main h-full flex-1 overflow-y-auto">{children}</main>
			</div>
		</>
	);
};

export default Layout;
